Added case to allow listing with AWS SDK
neicnordic/sda-s3proxy pull request #221
Opened 2022-06-01 11:55 UTC by dbampalikis

The pull request enables listing files in the sda-s3Proxy when using the AWS go SDK.

Before the introduced change, the proxy did not add the `bucket` to the url when trying to list files with the AWS SDK. Specifically, when using the `ListObjectsV2`, the proxy was attempting to list files using the `username` as `bucket` and therefore failing.

2022-06-01 12:10 UTC, aaperis approved these changes

2022-06-01 12:27 UTC, jbygdell requested changes
What happens if the user tries to list the root i.e. not adding the username to the path?

2022-06-01 12:49 UTC, dbampalikis commented on proxy.go
> +		} else if r.Method == http.MethodGet && (strings.Contains(r.URL.String(), "?location") || strings.Contains(r.URL.String(), "&prefix")) {
It doesn't seem to be a problem, but the fact that we don't have detailed tests for that is a concern. I have added a card for a test suite, but for now it's only about testing manually any corner case that comes to mind

2022-06-02 07:40 UTC, aaperis approved these changes

2022-06-02 09:16 UTC, jbygdell approved these changes

2022-06-02 09:16 UTC, merged