log CorrelationId on message sent in debug mode
neicnordic/sda-s3proxy pull request #329
Opened 2023-01-23 20:51 UTC by nanjiangshu

This PR solves #304 
The correlation ID will be logged in the debug mode when a message is sent to RabbitMQ at the completion of file uploading.

2023-01-25 11:52 UTC, jbygdell requested changes
This log message has no context.
According to #304 the entire MQ message should be logged, that includes message body and CorrelationID

2023-01-25 12:59 UTC, jbygdell commented
> @jbygdell the content of `body` contains no additional information than the checksum which has already been output at https://github.com/neicnordic/sda-s3proxy/blob/master/proxy.go#L361, and that's why @norling and me think it's enough to output just the correlationID, the only one not having a constant value in the MQ message. But if you think everything in the block https://github.com/neicnordic/sda-s3proxy/blob/master/messenger.go#L108-L114 should be output, I will modify it. Do you want it output as a JSON body or separately as strings?

The whole point of having all relevant information in the same message is to simplify the debugging work.
Instead of having to search and match multiple lines you can do a single search in Elasticsearch or run `kubectl logs -l role=inbox | grep correlationID`

2023-01-25 13:54 UTC, nanjiangshu commented
@jbygdell All items of the rabbitmq messages are logged by fix in the commit  f10fb23

2023-01-26 08:45 UTC, jbygdell commented
> @jbygdell All items of the rabbitmq messages are logged by fix in the commit [f10fb23](https://github.com/neicnordic/sda-s3proxy/commit/f10fb23f21ade8a39e8a5708697f8f1ade9c34f0)

There is no need to log static information and the log text is not relevant to the logged information.

2023-01-28 11:03 UTC, jbygdell requested changes

2023-01-28 11:03 UTC, jbygdell commented on messenger.go
> +	log.Debugf("confirmed delivery with delivery tag: %d, m.exchange: %v, m.routingKey: %v, Headers: %v, ContentEncoding: %v, ContentType: %v, DeliveryMode: %v, CorrelationId: %v, Priority: %v, Body: %v
```suggestion
	log.Debugf("Delivered message: %v, with correlation-ID: %v", string(body), corrID.String())
```

2023-02-02 07:41 UTC, dbampalikis approved these changes
Neat! Just rebase on master for this one too and it should be fine!

2023-02-02 10:23 UTC, aaperis approved these changes

2023-02-02 13:53 UTC, jbygdell approved these changes

2023-02-02 13:53 UTC, merged