Fix regexp no hit panic
neicnordic/sda-s3proxy pull request #332
Opened 2023-01-30 10:20 UTC by nanjiangshu

This PR closes #148 

It returned an error message when there is no valid matches for the regexp and thus avoid panic exit. 

**additional comments**
I feel a bit awkward with repeated coding and one might use `if else` to replace `switch` to solve the repeated coding problem. If you think it is necessary, I can do a refactoring but I guess the gain is little.

2023-01-30 13:46 UTC, jbygdell requested changes
* This check only needs to be performed once.
* It will require a dedicated test case
* Make use of what the `iss` filed in the token actually is

2023-02-01 11:07 UTC, jbygdell requested changes
Clean up the commits, it should at most be 3.

2023-02-01 11:07 UTC, jbygdell commented on userauth_test.go
> +	basIss, err := helper.CreateRSAToken(prKeyParsed, "ES256", "JWT", helper.WrongTokenAlgClaims)
```suggestion
	basIss, err := helper.CreateRSAToken(prKeyParsed, "RS256", "JWT", helper.WrongTokenAlgClaims)
```
wrong algorithm for this test block

2023-02-02 07:38 UTC, dbampalikis approved these changes
Looks good! Just rebase on master to be able to merge :)

2023-02-02 10:21 UTC, aaperis approved these changes

2023-02-02 13:54 UTC, jbygdell approved these changes

2023-02-02 13:54 UTC, merged